# Generated by Django 5.2.5 on 2025-09-03 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_cleanup_published_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'published'), ('published_at__isnull', True), _connector='OR'), name='published_at_null_unless_published'),
        ),
    ]
