version: "3.9"

services:
  web:
    image: ${TINYBLOG_IMAGE:-harbour.delin.tech/tinyblog/tinyblog-app:latest}
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /mnt/tinyblog-statics:/app/prodstatic
      - /mnt/tinyblog-data:/mnt
